//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactCrash
    {
        public int CrashPK { get; set; }
        public string CrashNumber { get; set; }
        public int DateSK { get; set; }
        public Nullable<System.DateTime> CrashTime { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public string AccessControlCode { get; set; }
        public Nullable<short> Alcohol { get; set; }
        public string AlignmentCode { get; set; }
        public string ByPassCode { get; set; }
        public int CitySK { get; set; }
        public string PrimaryContributingFactorCode { get; set; }
        public string SecondaryContributingFactorCode { get; set; }
        public string DistrictZone { get; set; }
        public Nullable<short> PublicPropertyDamage { get; set; }
        public Nullable<short> RailRoadTrainInvolved { get; set; }
        public Nullable<short> HitAndRun { get; set; }
        public Nullable<short> Drugs { get; set; }
        public string InvestigatingAgencyCode { get; set; }
        public string LightingCode { get; set; }
        public string LocationTypeCode { get; set; }
        public Nullable<double> MilePost { get; set; }
        public string MannerCollisionCode { get; set; }
        public Nullable<short> SingleVehicle { get; set; }
        public string ParishCode { get; set; }
        public Nullable<int> PrimaryHighwayNumber { get; set; }
        public string PrimaryRoadName { get; set; }
        public Nullable<double> PrimaryDistance { get; set; }
        public string PrimaryDirection { get; set; }
        public string RoadwayConditionCode { get; set; }
        public string RoadwayRelationCode { get; set; }
        public string RoadwayTypeCode { get; set; }
        public int AgencySK { get; set; }
        public Nullable<double> SecondaryDistance { get; set; }
        public Nullable<short> Intersection { get; set; }
        public string SeverityCode { get; set; }
        public string CrashSeverityCode { get; set; }
        public string SurfaceConditionCode { get; set; }
        public string SurfaceTypeCode { get; set; }
        public Nullable<short> TruckBusInvolvement { get; set; }
        public string Troop { get; set; }
        public string WeatherCode { get; set; }
        public Nullable<short> ConstructionMaintenanceZone { get; set; }
        public Nullable<short> Fatality { get; set; }
        public string HighwayTypeCode { get; set; }
        public Nullable<short> PrimaryMeasurementMiles { get; set; }
        public string IntersectingRoadName { get; set; }
        public Nullable<short> Injury { get; set; }
        public Nullable<short> Pedestrian { get; set; }
        public Nullable<int> DateEntered { get; set; }
        public Nullable<int> DataChanged { get; set; }
        public Nullable<int> ProcessDate { get; set; }
        public Nullable<int> HSRGDate { get; set; }
        public Nullable<int> CrashOrigin { get; set; }
        public Nullable<short> Aggressive { get; set; }
        public Nullable<short> Distraction { get; set; }
        public Nullable<short> Inattentive { get; set; }
        public Nullable<short> RoadwayDeparture { get; set; }
        public Nullable<short> LaneDeparture { get; set; }
        public Nullable<short> NoRestraint { get; set; }
        public Nullable<short> PredictedAlcohol { get; set; }
        public Nullable<short> CMV { get; set; }
        public string CMVSeverityCode { get; set; }
        public Nullable<short> YoungDriver { get; set; }
        public Nullable<short> OlderDriver { get; set; }
        public Nullable<short> DOTDWorkZone { get; set; }
        public Nullable<short> DOTDWorkZone5 { get; set; }
        public Nullable<int> HighwayNumberSK { get; set; }
        public Nullable<int> Holiday { get; set; }
        public Nullable<short> HazMatInvolved { get; set; }
        public string HWYSectionsAK { get; set; }
        public string ControlSection { get; set; }
        public Nullable<double> LogMile { get; set; }
        public Nullable<int> AmbulanceCallTime { get; set; }
        public Nullable<int> AmbulanceArriveTime { get; set; }
        public Nullable<int> AmbulanceHospitalTime { get; set; }
        public Nullable<int> AmbulanceArrivalToHospitalTime { get; set; }
        public Nullable<int> LaneClosureTime { get; set; }
        public Nullable<short> ElevatedInterstateCrash { get; set; }
        public Nullable<short> AmbulanceCall { get; set; }
        public Nullable<short> AmbulanceArrive { get; set; }
        public Nullable<short> AmbulanceHospital { get; set; }
        public Nullable<short> AmbulanceArrivalToHospital { get; set; }
        public Nullable<short> LaneClosure { get; set; }
        public Nullable<short> Motorcycle { get; set; }
        public Nullable<short> Bicycle { get; set; }
        public Nullable<short> BusLarge { get; set; }
        public Nullable<short> BusSchool { get; set; }
        public Nullable<short> BusSmall { get; set; }
        public Nullable<short> HazMatReleasedInvolved { get; set; }
        public string BAC08 { get; set; }
    }
}
